# Generated by Django 4.2.6 on 2023-10-26 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("match", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="matchweek",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches",
                to="match.matchweek",
            ),
        ),
    ]
