# Generated by Django 4.2.6 on 2023-10-29 12:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("match", "0003_matchweek_finished"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="match",
            options={"ordering": ["start_date"]},
        ),
    ]
