# Generated by Django 4.2.6 on 2023-11-05 11:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("match", "0004_alter_match_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="matchweek",
            options={"ordering": ["start_date"]},
        ),
    ]
