# Generated by Django 4.2.6 on 2023-11-06 12:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("match", "0005_alter_matchweek_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="matchweek",
            name="matchweek",
        ),
    ]
