# Generated by Django 4.2.6 on 2023-11-06 13:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("match", "0006_remove_matchweek_matchweek"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchweek",
            name="matchweek",
            field=models.SmallIntegerField(
                default=1,
                help_text="Matchweek number (from 1 to n)",
                validators=[
                    django.core.validators.MinValueValidator(
                        1, "Matchweek number cannot be less than 1."
                    )
                ],
            ),
            preserve_default=False,
        ),
    ]
