version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=Bet_game_pl
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: .
    env_file:
      - .env
    command: bash -c "python BetGame_PremierLeague/manage.py makemigrations && python BetGame_PremierLeague/manage.py migrate && ./init.sh && python BetGame_PremierLeague/manage.py runserver 0.0.0.0:8000"
    container_name: bet_app
    volumes:
      - .:/app_bet
    ports:
      - "8000:8000"
