# Generated by Django 4.2.6 on 2023-10-25 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("league", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="currently_league",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams",
                to="league.league",
            ),
        ),
    ]
