# Generated by Django 4.2.6 on 2023-10-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_season_remove_league_season_league_emblem_team_crest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='team',
            name='club_colors',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='shortcut',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
