# Generated by Django 4.2.7 on 2023-11-16 21:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("league", "0003_remove_season_matchweek"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="last_league",
        ),
    ]
