# Generated by Django 4.2.7 on 2023-11-18 10:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("league", "0004_remove_team_last_league"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="currently_league",
        ),
    ]
