# Generated by Django 4.2.7 on 2023-12-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("league", "0005_remove_team_currently_league"),
    ]

    operations = [
        migrations.AlterField(
            model_name="season",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="season",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
