# Generated by Django 4.2.6 on 2023-10-29 12:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0002_profile_friends_profile_support_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="friends",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="friends",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
