# Generated by Django 4.2.7 on 2023-12-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_userscores_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userscores",
            name="kind",
            field=models.PositiveSmallIntegerField(
                choices=[("bet", "Bet"), ("event", "Event"), ("other", "Other")],
                default="bet",
            ),
        ),
    ]
