# Generated by Django 4.2.6 on 2023-10-30 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_profile_friends"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="friends",
            new_name="following",
        ),
        migrations.AddField(
            model_name="profile",
            name="description",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
