# Generated by Django 4.2.6 on 2023-11-04 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_rename_friends_profile_following_profile_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserScores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.IntegerField(default=0)),
                ("description", models.TextField(max_length=500)),
                ("got", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points",
                        to="users.profile",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="SeasonPoints",
        ),
    ]
