# Generated by Django 4.2.6 on 2023-10-22 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('away_team', models.ManyToManyField(related_name='bet_away', to=settings.AUTH_USER_MODEL)),
                ('draw', models.ManyToManyField(related_name='bet_draw', to=settings.AUTH_USER_MODEL)),
                ('home_team', models.ManyToManyField(related_name='bet_home', to=settings.AUTH_USER_MODEL)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='match.match')),
            ],
        ),
    ]
