# Generated by Django 4.2.6 on 2023-10-25 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("match", "0001_initial"),
        ("bet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bet",
            name="match",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="match.match"
            ),
        ),
    ]
