# Generated by Django 4.2.6 on 2023-10-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bet", "0002_alter_bet_match"),
    ]

    operations = [
        migrations.AddField(
            model_name="bet",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="bet",
            name="choice",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("home", "Home Team"),
                    ("draw", "Draw"),
                    ("away", "Away Team"),
                ],
                max_length=20,
            ),
        ),
    ]
