# Generated by Django 4.2.6 on 2023-10-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bet", "0003_bet_is_active_alter_bet_choice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bet",
            name="choice",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("home", "Home Team"),
                    ("draw", "Draw"),
                    ("away", "Away Team"),
                ],
                default="none",
                max_length=20,
            ),
        ),
    ]
