# Generated by Django 4.2.6 on 2023-10-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bet", "0004_alter_bet_choice"),
    ]

    operations = [
        migrations.AddField(
            model_name="bet",
            name="is_won",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
