# Generated by Django 4.2.6 on 2023-11-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bet", "0005_bet_is_won"),
    ]

    operations = [
        migrations.AddField(
            model_name="bet",
            name="risk",
            field=models.BooleanField(default=False),
        ),
    ]
