# Generated by Django 4.2.6 on 2023-11-06 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("match", "0006_remove_matchweek_matchweek"),
        ("bet", "0006_bet_risk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bet",
            name="match",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bets",
                to="match.match",
            ),
        ),
    ]
