# Generated by Django 4.2.6 on 2023-11-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bet", "0007_alter_bet_match"),
    ]

    operations = [
        migrations.AddField(
            model_name="bet",
            name="risk_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
