# Generated by Django 4.2.7 on 2023-12-27 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("start_date", models.DateTimeField(help_text="Y-M-D")),
                ("end_date", models.DateTimeField(help_text="Y-M-D")),
                (
                    "description",
                    models.TextField(blank=True, max_length=300, null=True),
                ),
                ("fee", models.IntegerField(default=0)),
                (
                    "first_place",
                    models.PositiveSmallIntegerField(
                        default=60,
                        help_text="The field that specifies the percentage win for 1st place.",
                    ),
                ),
                (
                    "second_place",
                    models.PositiveSmallIntegerField(
                        default=30,
                        help_text="The field that specifies the percentage win for 2nd place.",
                    ),
                ),
                (
                    "third_place",
                    models.PositiveSmallIntegerField(
                        default=10,
                        help_text="The field that specifies the percentage win for 3rd place.",
                    ),
                ),
                ("is_finished", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("before", "Before"),
                            ("now", "Now"),
                            ("finished", "finished"),
                        ],
                        default="before",
                        max_length=25,
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True, related_name="events", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, max_length=500)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("canceled", models.BooleanField(default=False)),
                ("is_accept", models.BooleanField(default=False)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="event.event"
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="got_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
