# Generated by Django 4.2.7 on 2023-11-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0003_event_is_finished_alter_event_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("before", "Before"),
                    ("now", "Now"),
                    ("finished", "finished"),
                ],
                default="before",
                max_length=25,
            ),
        ),
    ]
